services:
  web:
    build: .
    volumes:
      - ./application/config/:/var/www/html/application/config/:rw
      - ./assets/qslcard/:/var/www/html/assets/qslcard/:rw
      - ./backup/:/var/www/html/backup/:rw
      - ./updates/:/var/www/html/updates/:rw
      - ./uploads/:/var/www/html/uploads/:rw
    depends_on:
      - db
    links:
      - db
    ports:
      - "80:80"
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
