services:
  web:
    build: .
    volumes:
      - ./assets/qslcard/:/var/www/html/assets/qslcard/
      - ./backup/:/var/www/html/backup/
      - ./updates/:/var/www/html/updates/
      - ./uploads/:/var/www/html/uploads/
    depends_on:
      - db
    links:
      - db
    ports:
      - "80:80"
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
      - ./install/assets/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
